from typing import Literal

from pydantic import BaseModel, Field


class AgentCitation(BaseModel):
    source: str = Field(description="Citation source identifier.")
    doc_id: str = Field(description="Indexed document id.")
    chunk_id: str = Field(description="Indexed chunk id.")
    snippet: str = Field(description="Retrieved text snippet.")
    page_number: int | None = Field(
        default=None,
        description="Optional page number when citation comes from PDF ingestion.",
    )


class AgentAskRequest(BaseModel):
    question: str = Field(min_length=1, description="User question for the agent.")
    doc_id: str = Field(description="Document id used to scope retrieval for this request.")
    session_id: str | None = Field(
        default=None,
        description="Optional session id used for tool context.",
    )
    product_name: str | None = None
    product_version: str | None = None
    document_types: list[str] = Field(default_factory=list)
    knowledge_space_id: str | None = None


class AgenticAskRequest(BaseModel):
    question: str = Field(min_length=1, description="Question for the corrective RAG graph.")
    doc_id: str | None = Field(
        default=None,
        description=(
            "Optional exact document scope. Omit it to search every accessible document "
            "matching the metadata filters."
        ),
    )
    product_name: str | None = None
    product_version: str | None = None
    document_types: list[str] = Field(default_factory=list)
    knowledge_space_id: str | None = None


class AgentAskResponse(BaseModel):
    status: str = Field(description="Execution status.")
    cache_status: Literal["hit", "miss"] = Field(
        description="Semantic cache lookup status for this answer.",
    )
    refined_query: str = Field(description="Refined query used for cache/retrieval.")
    answer: str = Field(description="Final answer generated by the agent.")
    steps: int = Field(description="Number of loop iterations used.")
    tools_used: list[str] = Field(description="List of tool names called by the agent.")
    citations: list[AgentCitation] = Field(
        default_factory=list,
        description="Optional citations extracted from retrieved context.",
    )
